# Singleton resource: manages the one TrueCommand service configuration on
# the system. Terraform destroy only removes it from state; the
# configuration (including any stored api_key) is left in place on TrueNAS.
#
# SAFETY: setting "enabled" to true starts a real connection attempt from
# this system to a TrueCommand instance (self-hosted or iX-hosted) using
# "api_key" -- a real external side effect, not a mere local configuration
# change. Leave "enabled" unconfigured (as below) to bring this resource
# under Terraform management purely for its read-only status attributes
# (status, status_reason, remote_url, remote_ip_address) without asserting
# any particular connection state, or set it explicitly to false to ensure
# TrueCommand stays disabled.
resource "truenas_truecommand_config" "config" {
  api_key = var.truecommand_api_key # 16-character key generated by iX Portal
}

variable "truecommand_api_key" {
  type      = string
  sensitive = true
  default   = null
}
