// Copyright TrueNAS 2026
// SPDX-License-Identifier: MPL-2.0

package truecommand_config

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/truenas/terraform-provider-truenas/internal/client"
)

var _ datasource.DataSource = &TrueCommandConfigDataSource{}

// TrueCommandConfigDataSource implements the truenas_truecommand_config
// data source.
type TrueCommandConfigDataSource struct{ client *client.Client }

// NewDataSource returns a new TrueCommandConfigDataSource.
func NewDataSource() datasource.DataSource { return &TrueCommandConfigDataSource{} }

func (d *TrueCommandConfigDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_truecommand_config"
}

func (d *TrueCommandConfigDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dschema.Schema{
		Description: "Reads the current TrueNAS TrueCommand service configuration and connection status. " +
			"Takes no arguments: there is exactly one TrueCommand configuration per TrueNAS system. Makes no " +
			"changes — see the truenas_truecommand_config resource's schema description for the safety notes " +
			"around the \"enabled\" field and \"api_key\"'s Sensitive-but-not-write-only treatment.",
		Attributes: map[string]dschema.Attribute{
			"id": dschema.StringAttribute{
				Computed:    true,
				Description: "Fixed identifier for this singleton: always \"truecommand_config\".",
			},
			"enabled": dschema.BoolAttribute{
				Computed:    true,
				Description: "Whether this system is enabled to connect to a TrueCommand instance.",
			},
			"api_key": dschema.StringAttribute{
				Computed:    true,
				Sensitive:   true,
				Description: "16-character API key generated by iX Portal, used to authenticate with TrueCommand services. Null when not configured.",
			},
			"status": dschema.StringAttribute{
				Computed:    true,
				Description: "Current connection status with the TrueCommand service (e.g. CONNECTED, CONNECTING, DISABLED, FAILED).",
			},
			"status_reason": dschema.StringAttribute{
				Computed:    true,
				Description: "Human-readable explanation of the current TrueCommand connection status.",
			},
			"remote_url": dschema.StringAttribute{
				Computed:    true,
				Description: "URL of the connected TrueCommand instance. Null if not connected.",
			},
			"remote_ip_address": dschema.StringAttribute{
				Computed:    true,
				Description: "IP address of the connected TrueCommand instance. Null if not connected.",
			},
		},
	}
}

func (d *TrueCommandConfigDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected provider data",
			fmt.Sprintf("expected *client.Client, got %T", req.ProviderData),
		)
		return
	}
	d.client = c
}

func (d *TrueCommandConfigDataSource) Read(ctx context.Context, _ datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state TrueCommandConfigDataSourceModel

	raw, err := d.client.CallRead(ctx, "truecommand.config")
	if err != nil {
		resp.Diagnostics.AddError("Read TrueCommand configuration failed", err.Error())
		return
	}

	var api truecommandConfigAPI
	if err := json.Unmarshal(raw, &api); err != nil {
		resp.Diagnostics.AddError("Parse truecommand.config response", err.Error())
		return
	}

	resp.Diagnostics.Append(responseToDataSourceModel(&api, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
