// Copyright TrueNAS 2026
// SPDX-License-Identifier: MPL-2.0

package truecommand_config

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
)

func resourceSchema() schema.Schema {
	return schema.Schema{
		Description: "Manages the TrueNAS TrueCommand service configuration (truecommand.config/" +
			"truecommand.update): whether this system is connected to a TrueCommand instance, plus its " +
			"read-only connection-status metadata. This is a singleton resource — there is exactly one " +
			"TrueCommand configuration per TrueNAS system, so it is never created or deleted on TrueNAS; " +
			"Terraform create/update calls truecommand.update, and Terraform delete only removes the resource " +
			"from state (the configuration, including any stored api_key, is left in place)." +
			"\n\n" +
			"SAFETY (read before setting \"enabled\" to true): setting \"enabled\" to true starts a real " +
			"connection attempt from this system to a TrueCommand instance (self-hosted or iX-hosted) using " +
			"\"api_key\" — a real, external side effect, not a mere local configuration change (mirrors " +
			"truenas_tn_connect_config's cloud-enrollment risk). This provider's own tests never set \"enabled\" " +
			"to true. Leave \"enabled\" unconfigured, or set it explicitly to false, to manage this resource " +
			"without asserting any particular connection state." +
			"\n\n" +
			"\"enabled\" and \"api_key\" are the ONLY fields this resource ever writes: probed live and IDENTICAL " +
			"on both TrueNAS 25.10.4 and 26.0, truecommand.update's own accepts schema (core.get_methods) exposes " +
			"EXACTLY these two properties — there is no other writable field on either release. Every other " +
			"attribute below is Computed-only, sourced from truecommand.config." +
			"\n\n" +
			"\"api_key\" is Sensitive but deliberately NOT write-only: unlike a credential this provider has no " +
			"way to observe read back (see truenas_app_registry's \"password\" or truenas_vmware's \"password\"), " +
			"a decisive live probe (setting a throwaway api_key with enabled left false) confirmed " +
			"truecommand.config returns it VERBATIM, UNMASKED, on every read — see model.go's doc comment for the " +
			"full transcript. HCL cannot express \"clear this back to null\" once api_key has a real value set " +
			"through this resource (a shared Terraform framework limitation: an omitted Optional attribute and " +
			"one explicitly set to null are indistinguishable) — only ever setting it to a different value.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				Description:   "Fixed identifier for this singleton resource: always \"truecommand_config\".",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"enabled": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				Description: "Whether this system is enabled to connect to a TrueCommand instance. SAFETY: " +
					"setting this to true starts a real connection attempt to a TrueCommand instance using " +
					"\"api_key\" (see the resource description above) — a real, external side effect. This " +
					"provider's own tests never set this to true. Leave unconfigured (the default) to manage " +
					"this resource purely for its read-only status fields, or set explicitly to false to ensure " +
					"TrueCommand stays disabled. Change deliberately.",
				PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"api_key": schema.StringAttribute{
				Optional:  true,
				Computed:  true,
				Sensitive: true,
				Description: "16-character API key generated by iX Portal, used to authenticate with " +
					"TrueCommand services. Null when not configured. Sensitive but NOT write-only: read back " +
					"verbatim from truecommand.config (decisive live probe — see model.go's doc comment), unlike " +
					"a genuinely masked credential.",
				Validators:    []validator.String{stringvalidator.LengthBetween(16, 16)},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"status": schema.StringAttribute{
				Computed: true,
				Description: "Current connection status with the TrueCommand service. One of CONNECTED, " +
					"CONNECTING, DISABLED, FAILED (probed live).",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"status_reason": schema.StringAttribute{
				Computed:      true,
				Description:   "Human-readable explanation of the current TrueCommand connection status.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"remote_url": schema.StringAttribute{
				Computed:      true,
				Description:   "URL of the connected TrueCommand instance. Null if not connected.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"remote_ip_address": schema.StringAttribute{
				Computed:      true,
				Description:   "IP address of the connected TrueCommand instance. Null if not connected.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
		},
	}
}
