#!/usr/bin/env python3
"""Inventory every external Go module this provider depends on.

Classifies each module two ways:
  Direct   -- named in go.mod's require blocks (an intentional choice)
              vs Indirect (pulled in transitively).
  Runtime  -- compiled into the SHIPPED provider binary (built from `.`)
              vs Tooling-only (reached only by tests / docs generation and
              their transitive deps; never in the artifact users install).

Runtime modules are the security-relevant surface: a CVE there ships to
users. Tooling-only modules affect only this repo's dev/CI.

Regenerate with `make go-deps`. Data comes from `go list`, so this reflects
the current go.mod/go.sum exactly.

Usage: python3 scripts/list-go-deps.py [--check]
  (no args)  write DEPENDENCIES.md
  --check    exit 1 if DEPENDENCIES.md is stale (for CI)
"""
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "DEPENDENCIES.md")
SELF = "github.com/truenas/terraform-provider-truenas"

# One-line purpose for the direct (intentionally chosen) dependencies.
DIRECT_PURPOSE = {
    "github.com/gorilla/websocket":
        "WebSocket client — JSON-RPC 2.0 transport to TrueNAS `/api/current`",
    "github.com/hashicorp/terraform-plugin-framework":
        "Provider/resource/data-source framework (Terraform protocol v6)",
    "github.com/hashicorp/terraform-plugin-framework-validators":
        "Reusable schema attribute validators",
    "github.com/hashicorp/terraform-plugin-go":
        "Low-level plugin protocol + tftypes (framework dependency, also "
        "used directly)",
    "github.com/hashicorp/terraform-plugin-testing":
        "Acceptance-test harness (test code only)",
    "golang.org/x/crypto":
        "OpenSSH keypair generation in acceptance tests (`x/crypto/ssh`); "
        "test-only, not in the shipped binary. (SCRAM auth uses the stdlib "
        "`crypto/pbkdf2`+`hmac`+`sha512`, not this module.)",
}


def go(*args):
    return subprocess.run(
        ["go", *args], cwd=ROOT, check=True,
        capture_output=True, text=True,
        env={**os.environ, "GOTOOLCHAIN": "auto"},
    ).stdout


def go_directive():
    with open(os.path.join(ROOT, "go.mod"), encoding="utf-8") as fh:
        for line in fh:
            if line.startswith("go "):
                return line.strip().split(None, 1)[1]
    return "?"


def main():
    # All modules in the build list: path | version | indirect-bool.
    mods = {}
    for line in go("list", "-m", "-f",
                   "{{.Path}}|{{.Version}}|{{.Indirect}}", "all").splitlines():
        if not line or line.startswith(SELF + "|"):
            continue
        path, version, indirect = line.split("|")
        mods[path] = {
            "version": version,
            "direct": indirect != "true",
            "runtime": False,
        }

    # Modules whose packages are compiled into the shipped provider binary.
    runtime = set()
    for path in go("list", "-deps", "-f",
                   "{{if .Module}}{{.Module.Path}}{{end}}",
                   ".").splitlines():
        path = path.strip()
        if path and path != SELF:
            runtime.add(path)
    for path in runtime:
        if path in mods:
            mods[path]["runtime"] = True

    total = len(mods)
    n_direct = sum(1 for m in mods.values() if m["direct"])
    n_runtime = sum(1 for m in mods.values() if m["runtime"])

    def row(path):
        m = mods[path]
        d = "yes" if m["direct"] else ""
        r = "yes" if m["runtime"] else ""
        return f"| `{path}` | {m['version']} | {d} | {r} |"

    L = []
    L.append("# External Go Dependencies")
    L.append("")
    L.append(
        "Every external Go module in this provider's build list, generated by "
        "`scripts/list-go-deps.py` from `go list`. Regenerate with "
        "`make go-deps`."
    )
    L.append("")
    L.append(
        f"- **Module directive:** `go {go_directive()}`"
    )
    L.append(
        f"- **{total}** external modules total: **{n_direct}** direct "
        f"(named in `go.mod`), {total - n_direct} indirect (transitive)."
    )
    L.append(
        f"- **{n_runtime}** modules are compiled into the shipped provider "
        f"binary (**Runtime**). The rest are reached only by tests / docs "
        f"generation and never ship to users."
    )
    L.append("")
    L.append(
        "**Runtime** marks the security-relevant surface: a vulnerability in "
        "a Runtime module ships to anyone who installs the provider; a "
        "Tooling-only module affects only this repo's dev/CI. Run "
        "`govulncheck ./...` (reachability-aware) to check the whole set."
    )
    L.append("")

    # Direct dependencies, with purpose.
    L.append("## Direct dependencies")
    L.append("")
    L.append("Named explicitly in `go.mod` — the intentional choices.")
    L.append("")
    L.append("| Module | Version | Runtime | Purpose |")
    L.append("|---|---|:--:|---|")
    for path in sorted(p for p in mods if mods[p]["direct"]):
        r = "yes" if mods[path]["runtime"] else ""
        purpose = DIRECT_PURPOSE.get(path, "")
        L.append(f"| `{path}` | {mods[path]['version']} | {r} | {purpose} |")
    L.append("")

    # Runtime closure (shipped binary).
    L.append("## Runtime closure (shipped in the provider binary)")
    L.append("")
    L.append(
        "Modules whose packages are compiled into the provider binary built "
        "from `.` (`go list -deps .`). This is what users execute."
    )
    L.append("")
    L.append("| Module | Version | Direct | Runtime |")
    L.append("|---|---|:--:|:--:|")
    for path in sorted(p for p in mods if mods[p]["runtime"]):
        L.append(row(path))
    L.append("")

    # Full inventory.
    L.append("## Full module inventory")
    L.append("")
    L.append(
        "Every external module in the build list "
        "(`go list -m all`), including test/docs-tooling transitives."
    )
    L.append("")
    L.append("| Module | Version | Direct | Runtime |")
    L.append("|---|---|:--:|:--:|")
    for path in sorted(mods):
        L.append(row(path))
    L.append("")

    content = "\n".join(L)

    if "--check" in sys.argv:
        existing = ""
        if os.path.exists(OUT):
            with open(OUT, encoding="utf-8") as fh:
                existing = fh.read()
        if existing.rstrip("\n") != content.rstrip("\n"):
            print("DEPENDENCIES.md is stale. Run: make go-deps",
                  file=sys.stderr)
            sys.exit(1)
        print("DEPENDENCIES.md up to date.")
        return

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(content + "\n")
    print(f"Wrote {os.path.relpath(OUT, ROOT)}: {total} modules "
          f"({n_direct} direct, {n_runtime} runtime).")


if __name__ == "__main__":
    main()
